FPGA-Research/FABulous

.github/workflows/fabric_gen.yml, .github/workflows/python-app.yml
Add basic file testing that fabric_gen.py does not contain syntax errors
=> Add ci actions file for fabric_gen.py

Dockerfile, docs/FABulous_docker.md
This branch adds a Dockerfile supporting an environment to run the fabric generation flow in. It does not currently make nextpnr - this is currently in progress.
=> Add dockerfile

docs/source/FPGA_CAD-tools/nextpnr.rst
Just one final PR to add a change I missed previously
=> Minor docs and readme fixes 2

docs/source/FPGA_CAD-tools/vpr.rst, fabric_generator/fabric_gen.py
This PR removes the requirement for custom XML to contain no whitespace in the num_pb value specification.
=> Custom xml whitespace

fabric_generator/fabric_gen.py
This changes the way that FABulous converts internal coordinates into VPR coordinates, FABulous now uses south-positive vertical indexing just like VPR. The unnecessary conversion has therefore been removed (and one minor fix to make sure the VPR flow closes some files it opens is also added here).
=> Update vpr coords

docs/source/contact.rst, docs/source/fabric_definition.rst, docs/source/simulation/emulation.rst, docs/source/simulation/simulation.rst
This PR just cleans up some typos, ambiguous sections and out-of-date information in the docs.
=> Polish docs

fabric_files/fabric_icarus_example/.gitignore, fabric_files/fabric_icarus_example/fabulous_tb.v, fabric_files/fabric_icarus_example/run_simulation.sh
Signed-off-by: gatecat <gatecat@ds0.me>
=> icarus: Use faster&smaller FST instead of VCD

fabric_generator/fabric_gen.py
@KelvinChung2000 would you be able to review?
=> fabric_gen: Fix user clock connectivity between supertiles

fabric_generator/fabric_gen.py
This enables top level ports other than BRAM or IO to be supported automatically based on the external bel ports, without having to modify the top level wrapper generator to support such functionality.
=> Make top level wrapper generation more flexible

fabric_generator/file_parser.py
Fixing the error in `file_parser.py`
=> Fixing file_parser.py for MaxFramesPerCol Issue? #115

.gitignore
Simple change, just adds pycache directories to gitignore so no-one accidentally commits cache files!
=> Add pycache dirs to git ignore

fabric_generator/model_generation_npnr.py
Fixes #143, thanks again @IAmMarcelJung for the spot!
=> Correct bel.txt comment

FABulous.py
Some of the lines get deleted by mistake, adding them back to make sure the simulation command is working.
=> Adding back the line that is deleted by mistake

FABulous/FABulous.py, docs/requirements.txt, docs/source/Usage.rst
Add functions to handle global and project specific environment variables and .env files.
Add commandline parameter to pass global or project specific .env files.
Add docs for .env. 
Remove unnecessary load_writer_from_env function.
=> Add better handling for environment variables

FABulous/fabric_generator/file_parser.py
Fix wrong number of arguments in vhdl_belMapProcessing() call.
Fix wrong indentation in parseBelFile() and add check for empty portname or direction.
=> Fix VHDL fabric generation

README.md, docs/source/Usage.rst
docs: Add note about tkinter on older Ubuntu versions
=> docs: Add note about tkinter on older Ubuntu versions

FABulous/fabric_generator/fabric_gen.py
Add check if configMem files needed to be generated for a tile. Tile_configMem.csv and also Tile_configMem.v were always generated, even if they are not needed for a tile.
Remove hardcoded NoConfigBit parameters in eFPGA.v and supertile tops, since they are not needed and cause linter issues.
=> fabric_gen: Generate configMem files only if needed

FABulous/fabric_generator/fabric_gen.py, docs/source/Usage.rst, docs/source/fabric_definition.rst
This PR fix some issues in the generated fabric RTL code, which caused some linter warnings. 
The issues were reported by @IAmMarcelJung. 
The commits in this PR are pretty much independent, so please no squash merge.
=> Fix some issues in generated verilog

.gitignore, FABulous/FABulous.py, FABulous/FABulous_CLI/FABulous_CLI.py, FABulous/FABulous_CLI/helper.py, docs/source/Usage.rst, pyproject.toml, requirements.txt
This is just a test to check if we can automate package distribution to pypi in future releases. 
Just picked a commit from my other PR to dev, and merge it in the prepared branch for deployment testing.
I'll merge this straight in the branch, to check if the deployment is triggered.
=> Test: Evaluate automated publishing to TestPyPi 

FABulous/fabric_generator/file_parser.py
Parsing using yosys leads to changes in the fabric netlist, which leads to incompatable bitstream. 
Updated to use the port name to look for the attribute from the netlist instead of directly finding the attribute from the netlist. 
I have checked against the 1.0 LUT4AB tile. Now `LA_I0_input` mux is starting at config bit 112 instead of 113. And `LA_EN` at bit 121.  
Let me know if this does not fully fix the problem.
=> Fix: Bitstream incompatibility between dev and main

.github/workflows/release_please.yml
Set up the release please workflow.
=> chore: release workflow

FABulous/FABulous.py, FABulous/FABulous_API.py, FABulous/FABulous_CLI/FABulous_CLI.py, FABulous/FABulous_CLI/cmd_synthesis.py, FABulous/FABulous_CLI/helper.py, FABulous/FABulous_settings.py, FABulous/fabric_cad/gen_bitstream_spec.py, FABulous/fabric_generator/gen_fabric/fabric_automation.py, FABulous/fabric_generator/parser/parse_csv.py, docs/source/conf.py, pyproject.toml, requirements.txt, tests/CLI_test/conftest.py, tests/CLI_test/test_CLI.py, tests/CLI_test/test_arguments.py, tests/CLI_test/test_helper.py, tests/fabric_gen_test/configmem_test/test_configmem_rtl.py, tests/fabric_gen_test/configmem_test/test_gen_configmem.py, tests/fabric_gen_test/configmem_test/test_parse_configmem.py, tests/fabric_gen_test/conftest.py, tests/fabric_gen_test/test_intergration.py
Centralise all the environment variable settings using [Pydantic-settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/).
Add sub dependency group
=> chore: centralise all settings

pyproject.toml, requirements.txt, tests/CLI_test/conftest.py, tests/CLI_test/test_CLI.py, tests/conftest.py, tests/guide.md, tests/reference_tests/.gitignore, tests/reference_tests/README.md, tests/reference_tests/__init__.py, tests/reference_tests/conftest.py, tests/reference_tests/helpers.py, tests/reference_tests/reference_projects_test.py
A pytest-based framework for testing FABulous against reference projects with regression testing capabilities.
See [tests/reference_tests/README.md](https://github.com/EverythingElseWasAlreadyTaken/FABulous/blob/1aa3e6a6d244599a3eae93812e02164f9aa20dfd/tests/reference_tests/README.md) for more information.
These are the executed tests:
https://github.com/FPGA-Research/FABulous-demo-projects/blob/main/reference_projects_config.yaml
=> test: Add reference tests

FABulous/FABulous.py, FABulous/FABulous_CLI/helper.py
Update oss cad install on the typer method to allow no dir (default to user/.fabulous)
=> fix: typer CLI oss-cad-install

FABulous/fabric_definition/Tile.py, FABulous/fabric_definition/Wire.py, ruff.toml
Enable postional argument checks.
=> chore: enable PYI063 for ruff

FABulous/FABulous.py, FABulous/FABulous_settings.py, docs/source/Usage.rst, tests/utils_test/test_FABulous_settings.py
Enable debug mode if the the `FAB_DEBUG` is set in the environment.
User input in the CLI override the settings.
=> feat: add debug env variable
