.github/workflows/fabric_gen.yml
fabric_generator/fabric_gen.py
fabric_generator/run_fab_flow_nextpnr_pair.sh

As mentioned in #5, FABulous' current method of checking arguments is not ideal as it converts arguments to a string and checks for presence of a substring, meaning that valid flags that are substrings of other valid flags can cause issues. This PR resolves this by creating a processed list of all arguments (by removing surrounding whitespace and making lower case), and checking the presence of valid flags within this list.

Fix argument checks

---

fabric_generator/fabric_gen.py
fabric_generator/fabric_gen_v3.py

Currently, having multiple tile types in the fabric csv file that contain BELs with the same name will lead to multiple, conflicting definitions of these bels. This PR fixes this bug by keeping track of all BELs processed in any tile type, and avoiding repeats.

Fix multiple tile bel recurrence bug

---

docs/source/Usage.rst

Minor change to the documentation fixing the mistake pointed out [here](https://github.com/FPGA-Research-Manchester/FABulous/issues/13).

Update to correct component name

---

fabric_generator/fabric_gen.py

This contains a few fixes and updates for the VPR flow:
- Widen the scope of doneBels so that the same BEL can appear in different tiles. This was fixed in a previous PR, but seems like it was unintentionally undone at some point.
- Update default custom XML for LUTs so that it matches the latest LUT design
- Fix the x_ and y_ list sizes as they were previously the wrong way round
- Change the way that wire PTC numbers are assigned. It looks like when fabrics get larger, issues occur due to some kind of 16-bit integer overflow on the PTC (not sure when it gets handled as 16-bit but a PTC number of 2^15 somehow ends up being interpreted as -2^15) that eventually leads to VPR trying to give a vector a negative size and throwing an error. Previously these numbers were assigned inefficiently, …

Update VPR flow

---

fabric_generator/fabric_gen.py

This addresses Issue #26, and now uses length checks to check whether the necessary arguments are provided. It also cleans up some of the messy parsing that occurred from checking arguments in a list converted to a string, and checks whether there are any flags where arguments are expected (where a flag is considered to be a whitespace-free string beginning with a hyphen).

Update to improved argument checker when flags require arguments

---

fabric_generator/fabric_gen.py

Currently VPR doesn't assume the name of hanging sources/sinks in the fabric, which is a bit more flexible if more of these are added. However, this would require moderate modification to the fabric generator itself, and so it's probably safe to assume that the possible names are fixed as (VCC, VDD, GND). Making this assumption has a very significant effect on runtime, and without it the VPR flow isn't very usable for large fabrics.

Change to assume source/sink names by default

---

fabric_generator/run_fab_flow.sh
fabric_generator/run_fab_flow_nextpnr.sh
fabric_generator/run_fab_flow_nextpnr_pair.sh
fabric_generator/run_fab_flow_vpr.sh

Primarily, this PR fixes the issue described in #32 - as it turns out that was nothing to do with the implementation, and was actually an issue with the tiles used in the generic architecture being changed. The main run_fab_flow.sh script was updated to work with the correct tiles, but none of the others were - this is fixed now! This also adds argument checks to make sure the 2 arguments that are necessary are added to the flow scripts (so they can then be passed to top_wrapper_generator_with_BRAM.py).

Fix wrong tile bug & add flow script arg checks

---

.github/workflows/fabric_gen.yml

Minor fix, just updating the integers passed as arguments to `fabulous_top_wrapper_temp/top_wrapper_generator_with_BRAM.py` so that they reflect the clarification in the docs that terminal blocks should not be counted in the row and column count.

Update CI BRAM script args

---

fabric_generator/run_fab_flow.sh
fabric_generator/run_fab_flow_nextpnr.sh
fabric_generator/run_fab_flow_nextpnr_pair.sh
fabric_generator/run_fab_flow_vpr.sh

The part of the docs that clarifies that the flow scripts require arguments for the fabric size is the same bit that specifies these numbers exclude terminal blocks, so if you miss that and just go off the argument check message in the scripts themselves there's no indication to exclude terminal blocks. This just extends the message to clarify for all flow scripts.

Clarify terminal blocks are not included in flow script message

---

.github/workflows/build_docs.yml

The CI docs build test currently only runs when a PR is made to master - this sets it to run on pushes too so we have the same reassurance with changes made to master.

Update docs CI test to run on push

---

fabric_generator/README.md

As was just fixed with the ecosystem diagram in the main README, the image in the fabric_generator README was a broken Dropbox link - this is updated here to link to the figure used in the docs source.

Broken fabric_generator README image

---

fabric_files/fabric_init_verilog_example/MULADD.v
fabric_files/fabric_init_vhdl_example/MULADD.vhdl

To make a multiply signed, it's not sufficient just to sign extend the product - it's also necessary to sign extend both operands to the full width of the multiply.
Fixes #51

Fix MULADD sign extension

---

fabric_files/fabric_simulation_example/models_pack.v
fabric_files/fabric_simulation_example/models_pack_sim.v
fabric_files/generic/models_pack.v

The previous sim model was overly X-pessimistic and would e.g. output 0 if a LUT input was 'X' even if that input didn't affect the LUT function (for example a LUT4 used as a LUT2 with two other inputs don't care).
This uses the x-accurate behaviour of ?:, as used in Yosys' LUT models for example. As a side affect it seems to massively speed up simulations compared to the old case-based model, too.

sim: Switch to X accurate mux model

---

docs/source/Usage.rst
docs/source/contact.rst
docs/source/fabric_definition.rst
docs/source/index.rst

There are a couple of pages in the docs that were left as placeholders a very long time ago - since they've not been filled yet, this PR removes them from the navigation bar so they can no longer be navigated to. The files are still there under the assumption that the pages will eventually be finished - if we decide against this they should obviously be removed. Note that this leads to a couple of warnings when generating the docs (as Sphinx detects that there's no navigation to the pages).
There's also a bit of general docs clean up included here.

Prune and clean docs

---

fabric_files/fabric_simulation_example/models_pack.v
fabric_files/fabric_simulation_example/models_pack_sim.v
fabric_files/generic/models_pack.v

- Removing `reg X` from `cus_mux41` because not register and causing error when doing FPGA emulation

Update models_pack_sim.v & Update models_pack.v

---

fabric_files/fabric_icarus_example/fabulous_tb.v

T_top is inverted by the fabric in https://github.com/FPGA-Research-Manchester/FABulous/blob/01b3c4484c686a0f7df40a7bc3fb4433904abba8/fabric_files/generic/IO_1_bidirectional_frame_config_pass.v#L36, do the same in the testbench when comparing against the gold

icarus: Invert T_top in testbench

---

fabric_files/fabric_icarus_example/fabulous_tb.v

Previously, if the fabric failed in such a way that it is outputting `z` or `x`, `!=` would also evaluate to `x` and per verilog rules the if-path would not be taken.
Changing to `!==` means that if the fabric outputs `z` or `x` then the inequality will be true and the if statement executed, so a failure is properly reported at the end.

tb: Use strict equality check

---

fabric_files/fabric_icarus_example/fabulous_tb.v
fabric_files/generic/bitbang.v
fabric_files/generic/config_UART.v
fabric_generator/fabulous_top_wrapper_temp/ConfigFSM_template.v
fabric_generator/fabulous_top_wrapper_temp/Config_template.v
fabric_generator/fabulous_top_wrapper_temp/bitbang.v
fabric_generator/fabulous_top_wrapper_temp/config_UART.v
fabric_generator/fabulous_top_wrapper_temp/eFPGA_v3_top_sky130_with_BRAM_template.v

Init values are ignored for ASIC synthesis and so dangerous to rely on. Instead, add async resets everywhere so we can start the config logic in a known good state. This is intended as an alternative solution to #71, and generally to better comply with VLSI good practice.
@ruck314 can you confirm this fixes the Cadence Genus synthesis?

config: Use resets everywhere instead of init values

---

docs/source/Usage.rst
docs/source/simulation/simulation.rst

This replaces references to the old custom nextpnr fork with upstream nextpnr; and the associated new scripts.

docs: Update to new nextpnr-generic and scripts

---

.github/workflows/fabric_gen.yml
.gitmodules
fabric_cad/bit_gen.py
fabric_cad/synth/cells_map.v
fabric_cad/synth/cells_map_ff.v
fabric_cad/synth/ff_map.v
fabric_cad/synth/latches_map.v
fabric_cad/synth/prims.v
fabric_cad/synth/prims_ff.v
fabric_cad/synth/synth_fabulous.tcl
fabric_cad/synth/synth_fabulous_dffesr.tcl
fabric_files/fabric_emulation_example/build_test_design.sh
fabric_files/fabric_ghdl_example/build_test_design.sh
fabric_files/fabric_icarus_example/build_test_design.sh
fabric_generator/run_fab_flow.sh
fabric_generator/run_fab_flow_nextpnr.sh
fabric_generator/run_fab_flow_nextpnr_pair.sh

Move the remaining useful files (synthesis and bit gen) out of the nextpnr repo; and then remove the now-unnecessary submodule, with nextpnr support having landed upstream some months ago.

Remove obsolete nextpnr submodule

---

docs/source/FPGA-to-bitstream/Yosys compilation.rst
docs/source/FPGA_CAD-tools/yosys.rst
docs/source/Usage.rst

This makes the documentation changes I proposed in the #79 discussion, removing discussion of the previous synthesis script and giving instructions to use the pass that is now upstream in Yosys. If we merge this, then we can probably also get rid of all the synthesis stuff in the nextpnr fork. I think I've covered everywhere the old script was mentioned, but let me know if I've missed anything! I also suspect that the page on Yosys models (`docs/source/FPGA_CAD-tools/yosys.rst`) is pretty old, so it would be great if you could check that it's still accurate @gatecat.

Switch to upstream Yosys synthesis pass

---

fabric_generator/fabulous_top_wrapper_temp/eFPGA_top_template.v
fabric_generator/fabulous_top_wrapper_temp/top_wrapper_generator.py

This doesn't add any BRAM automatically (although they can still be manually connected in the hierarchy layer above top_wrapper); and automatically infers top level ports from the fabric with a standard indexing order (-y, x).

top_wrapper: Add generator for without-BRAM case

---

docs/source/index.rst
docs/source/references/index.rst

Currently the autogenerated code documentation added in #50 isn't accessible anywhere, as there are no links to it in the sidebar - this adds links to the contents of `docs/references`.

Include autogenerated code docs in sidebar

---

FABulous.py
fabric_files/FABulous_project_template_verilog/Test/fabulous_tb.v
fabric_files/FABulous_project_template_verilog/Test/run_emulation_sim.sh
fabric_generator/code_generation_VHDL.py
fabric_generator/code_generation_Verilog.py
fabric_generator/code_generator.py
fabric_generator/fabric_gen.py

This re-adds updated support for emulation; which enables fast testing of a bitstream against the fabric in simulation or on hardware by passing the bitstream via macros/parameters rather than simulating the entire configuration logic.
Compared to pre-refactor FABulous, there are two improvements:
- Tiles with custom permuted bitstream layouts work properly (e.g. the LUT4AB)
- The bitstream is passed through the hierarchy as a parameter rather than a wire, which will enable pre-flattening optimisations with Yosys, important for some of my future plans (like a cxxrtl sim experiment I did with the MPW2 demo design).
The first commit in the series is not related to the emulation but made debugging this along the way a lot easier, because I could actually see what exceptions occurred rather …

Add updated emulation support to refactored FABulous

---

fabric_files/FABulous_project_template_verilog/Fabric/models_pack.v
fabric_files/FABulous_project_template_verilog/Test/fabulous_tb.v

For Synopsis DC compiler, you can add the following before elaboration and synthesis to deal with the combinatorial loops from the switch matrix
```TCL
set_disable_timing [get_pins -hierarchical *switch_matrix/*BEG*]
```
However for Cadence Genus, you can not apply such constraints until after elaboration and synthesis.  This makes even the simplest eFPGA design take 20+ hours to build.  After the 20+ hours, Cadence Genus addes `cdn_loop_breaker` buffers in all combinatorial loop path to address the timing issue. 
Similar to how you manually add the `clk_buf` with respect to the silicon process primitive, I propose we do a similar strategy for the combinatorial loop paths in the model_pack. 
```verilog
module break_comb_loop(input A, output X);
NAME_OF_CONFIDENTIAL_PRIMITIVE_HERE …
```

Adding break_comb_loop to models_pack.v

---

fabric_generator/code_generator.py

The docs are currently failing to build on Read the Docs due to some Verilog examples in docstrings that contain macro operations. The backticks in these are interpreted as the beginning of an inline block, and Sphinx protests as they never get closed. This just escapes the backticks to avoid the warnings (as warnings cause build fails with our current Read the Docs config - I should update CI to do the same!)

docs: Escape backticks in Verilog definitions

---

.github/workflows/build_docs.yml
docs/Makefile

As mentioned in #98, our Read the Docs setup fails builds when they produce warnings - this keeps resulting in build failures on our Read the Docs site flying under the radar, as the CI is still passing. This passes a custom build command to the action we use to build the docs for CI that is the same as that run by the Makefile, save for the addition of a few flags Read the Docs gives - this means CI should now fail for builds that will fail on Read the Docs.
An alternative to this is to update the docs Makefile so that these flags are always provided, but maybe it's preferred that warnings don't affect users building them locally just because that's what Read the Docs happens to do. Equally though, you could argue that we don't want local doc builds out of sync with what's online - …

Fail docs CI on warning

---

fabric_cad/bit_gen.py

The bitstream generation code was generally fragile, and in particular broke down in T-shaped fabrics where it wasn't inserting the currently-necessary padding correctly.
Marking this as draft right now because it needs more testing; and although my T-shape bitstreams now work in sim there are still problems under investigation on hardware.

bit_gen: Refactor; fix T-shaped and other irregular fabrics

---

.readthedocs.yaml

[Our most recent docs build failed](https://readthedocs.org/projects/fabulous/builds/21823928/) as the system packages attribute that we set in `.readthedocs.yaml` is now deprecated. This just gets rid of the attribute which should hopefully fix it!

Fix docs build failing due to RTD deprecated attribute

---

FABulous.py
fabric_generator/model_generation_vpr.py

This should fix the issue noted in #104 - `genVPRRoutingResourceGraph` has no knowledge of the project directory so can't write to the `.FABulous` directory to create the `maxWidth.txt` file. This just adds the max width as part of a return tuple so that the file handling can be done in `FABulous.py` as is done elsewhere.

Move `maxWidth.txt` handling to `FABulous.py`

---

docs/source/Usage.rst
docs/source/conf.py
pyproject.toml

This just fixes a couple of English->German typos and removes an unnecessary flag in the docs (since we no longer have any submodules)

Fix minor typos and remove unnecessary flag in setup guide

---

fabric_generator/fabric.py

The numberOfColumns and numberOfRows attributes are switched, leading to an OutOfBoundsError for non-square-shaped fabrics; and to square-shaped fabrics being printed on their side.

Fix __repr__ function of Fabric

---

fabric_generator/fabric.py
geometry_generator/fabric_geometry.py
geometry_generator/sm_geometry.py

Fix of width/height calculation of the fabrics geometry, plus some tiny fixes
To calculate the fabrics width/height, the bottom right tile was used - tile generation starts at (0, 0), thus the location and dimensions of this tile was used to determine the overall width and height of the fabric by using its location and width/height. However, the tile can be a NULL-Tile, rendering it useless for determining the dimensions of the fabric. This fix should resolve the issue.

Dim calculation fix + small fixes

---

fabric_cad/README.md

The calculation of the addressable configuration bits seems to be wrong since j is given by 32 and i by 20 and i x j = 32 * 20 = 640. Also removed trailing whitespaces.

Fix the calculation of the addressable config bits

---

fabric_cad/bit_gen.py

#124 pointed out that the CSV representation of bitstreams is output into a FASM file instead of a CSV file - this fixes this and adds a couple of comments to be a little clearer. Also noticed a bug in the generation of this CSV, which was just thanks to some incorrect indentation so that's fixed here too.

Fix filetype confusion and CSV generation bug

---

docs/source/simulation/simulation.rst

This gets rid of some outdated references to simulation in the docs, closing #134

Fix outdated simulation docs

---

docs/source/simulation/simulation.rst

Just switches the formatting of the changes in #136 as I accidentally used MD instead of RST formatting and didn't catch it as my local installation is playing up. Sorry!

Fix rendering of simulation doc commands

---

FABulous.py

If an error/exception occurs inside the FABulous Shell it is not printed, only `False` is returned:
```
def onecmd(self, line):
try:
return super().onecmd(line)
except:
return False
```
You can easily test this by adding a syntax error to e.g. the `do_load_fabric` function:
```
def do_load_fabric(self, args=""):
"load csv file and generate an internal representation of the fabric"
args = self.parse(args)
asdf
....
```
The FABulous shell does not indicate that an error has occurred:
```
FABulous> load_fabric
FABulous> 
```
This PR fixes that:
```
FABulous> load_fabric
Traceback (most recent call last):
File "/home/leo/Projects/FABulous_fix/FABulous.py", line 276, in onecmd
return super().onecmd(line)
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/cmd.py", line 217, in onecmd
return …
```

Print traceback on error inside FABulous Shell

---

fabric_generator/fabric_gen.py

Fixing the file path problem, without fixing the FrameStrobe problem

Refactor file path handling in fabric_gen.py using pathlib

---

FABulous/fabric_generator/fabric_gen.py

Remove the double call of addComponentDeclarationForFile, which caused the ConfigMem for a VHDL tile got instantiated twice, while the tile code was generated.
@KelvinChung2000: I'm not sure how this affects with the shift register based configuration type. Could you please check, if I should rather remove the upper "addComponentDeclarationForFile" call in the generateTile function?

:fabric_gen: Fix VHDL ConfigMem gets instantiated twice per tile

---

geometry_generator/fabric_geometry.py

Fix an indexing error in geometry generation that caused FABulous to crash when the fabric had fewer tiles on the Y axis than on the X axis.

geometry_gen:fabric_geometry: Fix indexing error for smaller fabrics

---

README.md

Tiny change as mentioned in #210 to make sure it's actually documented that another set of deps is needed to build docs

Adds docs dependencies installation to README

---

FABulous.py
fabric_files/FABulous_project_template_verilog/Test/sequential_16bit_en_tb.v

As mentioned in #213, the generation of `.fst` files is currently broken, since the `-fst` flag is missing when calling `vvp`. 
This is fixed here. The second fix concerns the test bench `sequential_16bit_en_tb.v`, where the enable bit was not set for the user design, resulting in undefined signals. Since the simulation is meant for the fabric, it did still not fail, but the output values of the DUT were useless. 
The fix for the `.fst` file was not applied to `run_simulation.sh` since no waveform will be generated by default in this file.
In the future `sequential_16bit_en_tb.v` could be made more generic, but for now this is just a quick fix with the minimum required changes, so that at least the demo design is correctly simulated.

Fix .fst generation in run_simulation and correct signal generation for the demo design in the test bench

---

FABulous/FABulous.py

This PR contains some minor changes that were not committed before the merge of PR : #210 
They're based on some suggestions @IAmMarcelJung had provided.
The main change is adding '-v' / '--verbose' to toggle the formats of the logger for clarity purposes.
Log output by default: 
Log output with '-v':
Message colour still follow the level of the log:

Added toggle for log level + minor corrections.

---

FABulous/fabric_definition/Bel.py
FABulous/fabric_files/FABulous_project_template_verilog/Tile/DSP/DSP_bot/MULADD.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/LUT4AB/LUT4c_frame_config_dffesr.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/LUT4AB/MUX8LUT_frame_config_mux.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/RAM_IO/Config_access.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/RAM_IO/InPass4_frame_config_mux.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/RAM_IO/OutPass4_frame_config_mux.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/RegFile/RegFile_32x4.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/W_IO/Config_access.v
FABulous/fabric_generator/fabric_gen.py
FABulous/fabric_generator/file_parser.py

Currently in the verilog files containing user BEL, ports must be declared individually, an example of this would be as follows: 
```
module RegFile_32x4 (D0, D1, D2, D3, W_ADR0, W_ADR1, W_ADR2, W_ADR3, W_ADR4, W_en, AD0, AD1, AD2, AD3, A_ADR0, A_ADR1, A_ADR2, A_ADR3, A_ADR4, BD0, BD1, BD2, BD3, B_ADR0, B_ADR1, B_ADR2, B_ADR3, B_ADR4, UserCLK, ConfigBits);
parameter NoConfigBits = 2;// has to be adjusted manually (we don't use an arithmetic parser for the value)
// IMPORTANT: this has to be in a dedicated line
input D0; // Register File write port
input D1;
input D2;
input D3;
input W_ADR0;
input W_ADR1;
input W_ADR2;
input W_ADR3;
input W_ADR4;
input W_en;
output AD0;// Register File read port A
output AD1;
output AD2;
output AD3;
input A_ADR0;
input A_ADR1;
input A_ADR2;
input A_ADR3; …
```

Vector Support for User BEL in Verilog.

---

FABulous/fabric_generator/file_parser.py

PR adds warning for Individual Port Declaration as suggested by @KelvinChung2000.
Example:
-Edit- 
Message is now `...Individually declared rather than as a vector.`

Warning For Individual Port Declaration

---

FABulous/FABulous.py
FABulous/geometry_generator/geometry_gen.py

The title pretty much sais it all... 
I added the command in the FABulous2.0-development branch, is that correct?
Let me know if anything here should be changed.
The command basically just runs FABulator in a new process.
***Before this is merged***, I want to add an option to enable/disable logging to the start_FABulator command, as right now the output of FABulator is logged to the FABulous shell (Which can be very annoying if not intended).
I've pretty much got it all running locally already, but I'm not quite happy with how logging it enabled/disabled.
Ideally, you'd simpy be able to pass an additional flag such as -enable_logging, but I'm not sure how to do this in a clean way. Any suggestions are greatly appreciated!
In my quick and dirty solution, I basically just passed an …

Add start_FABulator command to be able to run FABulator from the FABulous shell

---

FABulous/fabric_files/FABulous_project_template_verilog/FABulous.tcl

Remove npnr parameter from FABulous.tcl, since it is not needed anymore, and throws an error.

fabric_files:verilog_template:FABulous.tcl: Remove npnr parameter

---

FABulous/FABulous.py
FABulous/fabric_generator/fabric_gen.py
FABulous/fabric_generator/file_parser.py

Fix backward compatibility to old project structure: 
- Add case for old tcl scripts in run_FABulous_bitstream.
- ConfigMemPath in fabric_gen:generateBitstreamSpec was set wrong, if a project used the old fabric.csv structure.
Remove unneeded get_path() function and use Path() instead of pathlib.Path()
Add check if external programs are installed

Fix backward compatibility to old project structure and some housekeeping 

---

.gitignore
FABulous/FABulous.py

Extend default paths for .env files to common folders.
Add ".env" and "venv" to gitignore.

FABulous: Extend .env default paths and update gitignore

---

FABulous/fabric_generator/fabric_gen.py

Fixes a typo in `fabric_gen` regarding UserClock wire generation in SuperTiles, which would otherwise break the netlist.
Verilator complains:
```
%Warning-UNUSEDSIGNAL: DSP.v:105:10: Signal is not driven, nor used: 'Tile_X0Y1_userCLKo'                                                                                                    
: ... note: In instance 'DSP'                                                                                                                                                                
105 |     wire Tile_X0Y1_userCLKo;
```
This has been tested with the default fabric.

Fix UserCLK wire generation in SuperTiles

---

FABulous/fabric_files/FABulous_project_template_verilog/Tile/RegFile/RegFile_32x4.v

`AD` and `BD` were initially assigned to  the outputs of `mem`, but were later reassigned based on `ConfigBits`. AFAIK, this is not valid Verilog. Since the intention is to choose between a combinatorial/registered version of `AD` and `BD`, I added two intermediate wires `AD_comb` and `BD_comb`.
This PR fixes synthesis with Yosys.

RegFile: Fix assignment to read data

---

FABulous/fabric_files/FABulous_project_template_verilog/Fabric/models_pack.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/LUT4AB/LUT4c_frame_config_dffesr.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/LUT4AB/MUX8LUT_frame_config_mux.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/RAM_IO/InPass4_frame_config_mux.v
FABulous/fabric_files/FABulous_project_template_verilog/Tile/RAM_IO/OutPass4_frame_config_mux.v
FABulous/fabric_files/FABulous_project_template_vhdl/Fabric/my_lib.vhdl
FABulous/fabric_files/generic/InPass4_frame_config_mux.v
FABulous/fabric_files/generic/MUX8LUT_frame_config_mux.v
FABulous/fabric_generator/fabric_gen.py

Now can correctly generate non power of 2 mux.
```verilog
//switch matrix multiplexer E6BEG4 MUX-5
assign E6BEG4_input = {A_O,W6END3,WW4END3,W1END2,W1END0};
cus_mux81_buf inst_cus_mux81_buf_E6BEG4 (
.A0(E6BEG4_input[0]),
.A1(E6BEG4_input[1]),
.A2(E6BEG4_input[2]),
.A3(E6BEG4_input[3]),
.A4(E6BEG4_input[4]),
.A5(GND0),
.A6(GND0),
.A7(GND0),
.S0(ConfigBits[76+0]),
.S0N(ConfigBits_N[76+0]),
.S1(ConfigBits[76+1]),
.S1N(ConfigBits_N[76+1]),
.S2(ConfigBits[76+2]),
.S2N(ConfigBits_N[76+2]),
.X(E6BEG4)
);
```
I have also updated the name of the my_mux2 to cus_mux21, to make them follow the same naming conversion for the other muxes.

Fixing non power of 2 mux generation 

---

.github/workflows/build_docs.yml
docs/requirements.txt

Add minimum required dependency versions to docs/requirements.txt
Add version to sphinx action in 'build_docs' workflow, since default sphinx version of the action is 2.44. Install dependencies and FABulous first before building docs.

docs: Fix build_docs workflow and add docs dependency versions

---

.github/workflows/fabric_gen.yml
README.md
docs/source/Usage.rst

Remove legacy python3.10 call.
Remove installation of python-tk since it is already included in the default binares since Python3.7.
Update docs and README.
Since we are using 'ubunut-latest' for the workflows, the workflows failed since python-tk was removed from the Ubunut PPA.

workflows: Update workflows for ubuntu 24

---

docs/readme.md
docs/source/conf.py

Add a readme for the docs with build instructions for the documentation.
Add sphinx.ext.imgconverter to conf.py, which is needed to convert svg files for the latexpdf output.
The extension uses ImageMagick to perform conversions and will not work if ImageMagick is not installed.

docs: Add readme.md for docs and add imgconverter to sphinx extensions.

---

.github/workflows/build_docs.yml

We want to add a dev version to read the docs server, so the build_docs workflow should also run on every PR on FABulous2.0-development.

workflows: Run build_docs also on dev branch PRs

---

docs/requirements.txt

Sphinx autodoc also needs the main requirements installed, otherwise the readthedocs build fails.

docs: Add main requrements to docs requirements

---

FABulous/fabric_generator/code_generation_VHDL.py

The generated VHDL code for module instantiations of switch matrix multiplexers, concatenated vectors with {}, which is not valid VHDL.
Replace {} with () for aggregation in VHDL.

code_gen_VHDL: Fix issue with VHDL module instantiation

---

FABulous/fabric_files/FABulous_project_template_verilog/Test/sequential_16bit_en_tb.v

This fixes #305 by correctly enabling and resetting the counter in the testbench used in the `run_simulation` command.
It should be noted that this still does not match the output of the script `run_simulation.sh`, since the command simulates the user design instead of the `counter.v` test design. I will open a discussion on what we want the `run_simulation` command to actually test.
@mole99 could you check if this resolves the issue of the wrong output on your end (according to the things I mentioned above)? I ofc did check it on my end, but better safe than sorry :)

Fix run_simulation output

---

FABulous/fabric_generator/fabric_gen.py

This PR fixes/improves how FrameData and FrameStrobe signals are connected within the fabric.
1. Tiles: Always generate FrameData ports
- Fixes #296
- This allows mixing tiles with no config bits and tiles with config bits in the same row
2. Remove special handling of first and last row
- Fixes #297
- This allows to have tiles with config bits in the first and last row (e.g. `N_IO`, `S_IO`)
3. Generalize handling of NULL tiles
- Supersedes #161
- A major improvement to how NULL tiles are currently handled
The general behavior is as follows:
For each tile connect the FrameData input port to the FrameData output port of the previous tile. If the previous tile is `NULL`, the tile before is used (if that one is `NULL` repeat again). If all tiles before the tile are `NULL`, connect directly to …

Improve FrameData and FrameStrobe handling

---

FABulous/fabric_generator/fabric_gen.py
FABulous/fabric_generator/file_parser.py

fabric_gen:
- Fix: Add missing `begin` / LogicStart in ConfigMem generation.
- Generate NoConfigBits Parameter in Tiles only if it has config bits.
- Remove unused/typo signal `resten` in top wrapper generation.
file_parser:
- Fix: Add individually_declared setting also in VHDL bel port parsing, since individual declared VHDL bel ports were detected and connected as vectors, which resulted in port mismatches.

fabric_generator: Fix broken VHDL fabric generation

---

FABulous/FABulous.py
FABulous/FABulous_CLI/FABulous_CLI.py
FABulous/FABulous_CLI/cmd_synthesis.py
FABulous/FABulous_CLI/helper.py
FABulous/fabric_generator/utilities.py

When entering the shell, now will move the current working directory to the project directory, and when exit will move the user back to the original point. 
This will make all relative paths always work relative to the current FABulous project. 
Some other minor migration to `pathlib`.
Typo fix.

Fixing changes after #291

---

.github/actions/prepare_FABulous_container/action.yaml
.github/workflows/fabric_gen.yml
FABulous/fabric_files/FABulous_project_template_verilog/Test/Makefile
FABulous/fabric_files/FABulous_project_template_verilog/Test/build_fabulous_fabric.tcl

Add a reusable workflow to prepare the workflow environment.
Make use of the reusable workflow.
Add a new workflow job, which runs our simulation based on the
Makefile flow. This makes the tests less dependent on the CLI
and test both workflows.

Add reusable workflow and add Makefile based test

---

FABulous/FABulous_CLI/helper.py

Make FAB_PROJ_DIR an absolute path to avoid problems when accessing it.

fix: Make FAB_PROJ_DIR env export an absolute path

---

FABulous/fabric_generator/fabric_gen.py

Fix the config mem path in the bitstream spec generation for legacy fabrics.

fix:fabric_gen: Bitstream spec gen for legacy fabrics

---

FABulous/fabric_generator/fabric_gen.py

The bitstream spec generation was wrong for non power of 2 MUX. The number of bits to encode a MUX was calculated by (muxsize.bit_length() -1). As an example, this results 3 config bits for a MUX15 and 4 bits for a MUX17, which is not correct.
We changed this to (muxsize - 1).bit_length() for the MUX encoding calculation. This results in the right number of config bits: MUX15: 4 bits, MUX16: 4 bits MUX17: 5 bits...

fix:fabric_gen: Bistream spec gen for non power of 2 MUX

---

FABulous/fabric_generator/fabric_gen.py

PR #314 fixed the config bit calculation for non power of two multiplexers, but the calculation of 'NoConfigBit' parameter in the switch matrix was not updated accordingly. This resulted in port mismatches in the switch matrix instantiation.

fix:fabric_gen: Wrong number of config bits in switch matrix

---

FABulous/geometry_generator/fabric_geometry.py

The geometry CSV output is based on a set.
The order of elements in Python set is non-deterministic.
This resulted in a different eFPGA_geometry.csv for every fabric run, even if nothing was changed in the fabric itself.

fix:fabric_geometry: Non-deterministic geometry CSV generation

---

FABulous/fabric_generator/fabric_gen.py

parseBelFile import was missing after #364.
Testworkflow failed silently, but this should be fixed with #366.

fix:fabric_gen Add parseBelFile import

---

FABulous/fabric_cad/bit_gen.py

Since #311 might still take some time to be merged and the fix sometimes collides with updates from the dev branch when only done locally I want to propose we get this small but important fix into the dev branch. 
All credit is given to @mole99, I just extracted it from his PR.
@EverythingElseWasAlreadyTaken Let me know if this is the correct way to get some feature out of another PR or if there is something smarter (e.g. cherry picking?).

Add the desync frame during the bitstream generation

---

FABulous/FABulous.py

OSS-CAD-Suite install needs to be done before the check for the .FABulous folder in the demo project.

fix:Install OSS-CAD-Suite without demo project

---

pyproject.toml
requirements.txt

Remove some trailing commas in requirements.txt, which could lead to errors in older pip versions and remove duplicate requirements.
Set lower base version of bitarray in pyproject.toml for better compatibility.

fix: requirements.txt format

---

pyproject.toml

We accidentally set the min version of bitarry in the pyproject.toml to 3.0.0 but we need features from 3.3.0.

fix: Set bitarry min version to 3.3.0

---

FABulous/FABulous.py
FABulous/FABulous_CLI/FABulous_CLI.py
FABulous/FABulous_CLI/helper.py
docs/source/Usage.rst
tests/CLI_test/test_arguments.py
tests/CLI_test/test_helper.py

Add the package version when creating a project. If the project version is less than the starting version, add a warning during package setup. 
It can further improve to raise errors when the project version and the package version have major version differences. But this can be done later.

feat: Add version number and checks

---

.github/workflows/backwards-compatibility.yml
FABulous/FABulous.py
FABulous/FABulous_API.py
FABulous/FABulous_CLI/FABulous_CLI.py
FABulous/FABulous_CLI/__init__.py
FABulous/FABulous_CLI/cmd_synthesis.py
FABulous/FABulous_CLI/helper.py
FABulous/FABulous_settings.py
FABulous/fabric_cad/gen_bitstream_spec.py
FABulous/fabric_definition/Yosys_obj.py
FABulous/fabric_generator/gen_fabric/fabric_automation.py
FABulous/fabric_generator/parser/parse_csv.py
FABulous/fabric_generator/parser/parse_hdl.py
docs/source/conf.py
pyproject.toml
tests/CLI_test/conftest.py
tests/CLI_test/test_CLI.py
tests/CLI_test/test_arguments.py
tests/conftest.py
tests/fabric_gen_test/test_intergration.py
tests/reference_tests/conftest.py
tests/reference_tests/helpers.py
tests/reference_tests/reference_projects_test.py
tests/utils_test/conftest.py
tests/utils_test/test_FABulous_settings.py
tests/utils_test/test_yosys_obj.py
uv.lock

Updated the context management to use `get_context` only, and this will only create the model once and automatically resolve all environment dependencies. This can be used as the base for all feature global settings. 
Removed dependency on `FAB_ROOT`. Now the project does not reference the installation dir directly. Project creation is now done via the `importlib.resources`. Global `.env` is now stored at user `$HOME/.fabulous`. And this can be used for all future installations and FABulous related cross-session assets. 
Transition from `argparse` based command to `typer`, which offers a much better looking interface and help message. This also makes creating new commands down the line much easier, such as `FABulous GUI` etc.  Full backwards compatibility in the interface is maintained, …

feat: better context management and new start interface

---

.readthedocs.yaml

Switch to uv bricked the RTD build. 
This should fix it. 
And should also add docs preview for PRs.

fix(docs): uv support for readthedocs

---

.github/workflows/release_please.yml

This might fix the error for the token generation, since no scope for the token was defined,
so it tried to generate a token for the whole Organization, which is not allowed for the APP.

chore[ci]: Set repository scope for token generaion for release please workflow

---

FABulous/fabric_definition/Bel.py
FABulous/fabric_generator/gen_fabric/gen_tile.py
FABulous/fabric_generator/parser/parse_hdl.py

The `individually_declared` flag was a legacy fix, before we had the Yosys based parsing for both, Verilog and VHDL.

chore: Remove deprecated individually declared flag in BEL parsing
